table 'Nutritional Data'
	lineageTag: 9978d3a4-e934-415e-a4bb-e384e50dd000

	column 'Food Code'
		dataType: int64
		formatString: 0
		lineageTag: 44d9b377-78a3-49e5-94b0-c9a59d3d141c
		summarizeBy: count
		sourceColumn: Food Code

		annotation SummarizationSetBy = Automatic

	column 'Food Description'
		dataType: string
		lineageTag: e4fbe05a-95a4-4a63-aa51-3949a6ea9364
		summarizeBy: none
		sourceColumn: Food Description

		annotation SummarizationSetBy = Automatic

	column 'Number of Servings'
		dataType: int64
		formatString: 0
		lineageTag: 1f6aa8e4-5f6f-4a60-af0c-4967d1100a0e
		summarizeBy: sum
		sourceColumn: Number of Servings

		annotation SummarizationSetBy = Automatic

	column 'Measure Description'
		dataType: string
		lineageTag: 2cfc032f-9283-414f-9f08-1a756a51142c
		summarizeBy: none
		sourceColumn: Measure Description

		annotation SummarizationSetBy = Automatic

	column 'Measure Weight (g)'
		dataType: double
		lineageTag: 2d350862-2d71-46cf-bf4f-b436124790f0
		summarizeBy: sum
		sourceColumn: Measure Weight (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Energy (kcal)'
		dataType: int64
		formatString: 0
		lineageTag: 931cfe81-2ca6-4a6e-a891-5d966e9ebab9
		summarizeBy: sum
		sourceColumn: Energy (kcal)

		annotation SummarizationSetBy = Automatic

	column 'Protein (g)'
		dataType: double
		lineageTag: 50a60b36-973d-4006-b327-58d39c0c0e68
		summarizeBy: sum
		sourceColumn: Protein (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carbohydrate (g)'
		dataType: double
		lineageTag: b9eeec45-db03-418d-a1fb-1eef47477a96
		summarizeBy: sum
		sourceColumn: Carbohydrate (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Fat (g)'
		dataType: double
		lineageTag: 5e1ca1a0-c1eb-4949-b43c-9dd756042268
		summarizeBy: sum
		sourceColumn: Total Fat (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Sugars (g)'
		dataType: double
		lineageTag: f75666f6-def3-4006-b6ec-5f3424c9785e
		summarizeBy: sum
		sourceColumn: Total Sugars (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dietary Fiber (g)'
		dataType: double
		lineageTag: cf3cedb7-d85c-472c-b7e1-0aba8244dfcf
		summarizeBy: sum
		sourceColumn: Dietary Fiber (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Water (g)'
		dataType: double
		lineageTag: 9cc80ed2-8269-4426-80b5-c8085c3bacac
		summarizeBy: sum
		sourceColumn: Water (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cholesterol (mg)'
		dataType: int64
		formatString: 0
		lineageTag: e626437a-b605-420d-a85b-544ba15dce93
		summarizeBy: sum
		sourceColumn: Cholesterol (mg)

		annotation SummarizationSetBy = Automatic

	column 'Total Saturated (g)'
		dataType: double
		lineageTag: 68557020-c39c-499f-bfac-61f2cc147b84
		summarizeBy: sum
		sourceColumn: Total Saturated (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '4:0 (g)'
		dataType: double
		lineageTag: 0a179415-f4c8-4743-90a9-44622a3744e7
		summarizeBy: sum
		sourceColumn: 4:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '6:0 (g)'
		dataType: double
		lineageTag: b53407f3-8110-49c3-8d07-7940e47fbd1b
		summarizeBy: sum
		sourceColumn: 6:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '8:0 (g)'
		dataType: double
		lineageTag: b366f33f-d122-49cd-9a9c-08afca805e12
		summarizeBy: sum
		sourceColumn: 8:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '10:0 (g)'
		dataType: double
		lineageTag: 47dd392d-a34f-409b-b296-9305974985b3
		summarizeBy: sum
		sourceColumn: 10:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '12:0 (g)'
		dataType: double
		lineageTag: a099c424-4d18-43e1-969c-b5e3ce1d0c30
		summarizeBy: sum
		sourceColumn: 12:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '14:0 (g)'
		dataType: double
		lineageTag: d7f74922-ab9b-43e8-9342-57994a3ef8f6
		summarizeBy: sum
		sourceColumn: 14:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '16:0 (g)'
		dataType: double
		lineageTag: c5204f3b-0365-43fd-bd26-d494252a0e57
		summarizeBy: sum
		sourceColumn: 16:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '18:0 (g)'
		dataType: double
		lineageTag: f7c11676-d9fe-42af-853e-9ac9846cf556
		summarizeBy: sum
		sourceColumn: 18:0 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Monounsaturated (g)'
		dataType: double
		lineageTag: d9866a76-b8b6-455d-bee6-324c3e553fc7
		summarizeBy: sum
		sourceColumn: Total Monounsaturated (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '16:1 (g)'
		dataType: double
		lineageTag: cf823102-ffb8-4636-ac5e-dba6dc5bddf6
		summarizeBy: sum
		sourceColumn: 16:1 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '18:1 (g)'
		dataType: double
		lineageTag: e9ff5530-c5f5-4d3d-b04b-5046d772ddf4
		summarizeBy: sum
		sourceColumn: 18:1 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '20:1 (g)'
		dataType: double
		lineageTag: b5ca048e-5e50-492f-a61e-ead39bad705f
		summarizeBy: sum
		sourceColumn: 20:1 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '22:1 (g)'
		dataType: double
		lineageTag: 4abd3a3c-f62a-4348-aebe-0fc8083960cc
		summarizeBy: sum
		sourceColumn: 22:1 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Polyunsaturated (g)'
		dataType: double
		lineageTag: 6f7843b6-4e18-427e-ba2d-24957e3319e5
		summarizeBy: sum
		sourceColumn: Total Polyunsaturated (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '18:2 (g)'
		dataType: double
		lineageTag: 76dc1c3f-8cb4-459f-8779-6b2279d2ca36
		summarizeBy: sum
		sourceColumn: 18:2 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '18:3 (g)'
		dataType: double
		lineageTag: a1f8b36b-d0a8-4089-8827-857522f0afcd
		summarizeBy: sum
		sourceColumn: 18:3 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '18:4 (g)'
		dataType: int64
		formatString: 0
		lineageTag: 79c0c680-8363-4b24-a9c7-f3bcb733757c
		summarizeBy: sum
		sourceColumn: 18:4 (g)

		annotation SummarizationSetBy = Automatic

	column '20:4 (g)'
		dataType: double
		lineageTag: d10d0468-23f0-4860-bf26-52250a6b9a63
		summarizeBy: sum
		sourceColumn: 20:4 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '20:5 n-3 (g)'
		dataType: double
		lineageTag: ccdd1908-71eb-4780-9295-a4f3deb5db97
		summarizeBy: sum
		sourceColumn: 20:5 n-3 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '22:5 n-3 (g)'
		dataType: double
		lineageTag: ad115344-8a9d-47d6-8410-bb7fc3084569
		summarizeBy: sum
		sourceColumn: 22:5 n-3 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '22:6 n-3 (g)'
		dataType: double
		lineageTag: 2d57133d-473d-455e-ba38-af8dc60d0e04
		summarizeBy: sum
		sourceColumn: 22:6 n-3 (g)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Calcium (mg)'
		dataType: int64
		formatString: 0
		lineageTag: 8e66e8ee-8a6e-4c23-99b4-0fcda14f4554
		summarizeBy: sum
		sourceColumn: Calcium (mg)

		annotation SummarizationSetBy = Automatic

	column 'Iron (mg)'
		dataType: double
		lineageTag: a3d10030-fa0b-4102-bd63-bf239e50cc0c
		summarizeBy: sum
		sourceColumn: Iron (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Magnesium (mg)'
		dataType: int64
		formatString: 0
		lineageTag: aa94ac84-3965-46cb-bcf4-94f49c00ed97
		summarizeBy: sum
		sourceColumn: Magnesium (mg)

		annotation SummarizationSetBy = Automatic

	column 'Phosphorus (mg)'
		dataType: int64
		formatString: 0
		lineageTag: b95e43c7-82fa-4cf2-b0cb-439ca7bb05f2
		summarizeBy: sum
		sourceColumn: Phosphorus (mg)

		annotation SummarizationSetBy = Automatic

	column 'Potassium (mg)'
		dataType: int64
		formatString: 0
		lineageTag: 63bdfdef-f92e-4f8a-b8d5-92b6824c3612
		summarizeBy: sum
		sourceColumn: Potassium (mg)

		annotation SummarizationSetBy = Automatic

	column 'Sodium (mg)'
		dataType: int64
		formatString: 0
		lineageTag: 1b8a642f-7694-4525-abf2-5d5655e33a1f
		summarizeBy: sum
		sourceColumn: Sodium (mg)

		annotation SummarizationSetBy = Automatic

	column 'Zinc (mg)'
		dataType: double
		lineageTag: 9370c2d2-a6a9-4736-8448-a53a4e5fb8ca
		summarizeBy: sum
		sourceColumn: Zinc (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Copper (mg)'
		dataType: double
		lineageTag: f3033746-a462-411c-bba5-3d774db9b1a8
		summarizeBy: sum
		sourceColumn: Copper (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Selenium (mcg)'
		dataType: double
		lineageTag: bb196787-550a-48aa-bfb9-3c42d95d78cb
		summarizeBy: sum
		sourceColumn: Selenium (mcg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit A, RAE (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: c5047c4a-dac8-47f9-ab13-aeb862848e94
		summarizeBy: sum
		sourceColumn: Vit A, RAE (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Retinol (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: 1b439faa-32ee-4965-922c-566801326c84
		summarizeBy: sum
		sourceColumn: Retinol (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Carotene, Alpha (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: 1150b882-ab36-412b-8793-55bce527a733
		summarizeBy: sum
		sourceColumn: Carotene, Alpha (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Carotene, Beta (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: d9c4ee3f-def0-40cf-9528-013940945b70
		summarizeBy: sum
		sourceColumn: Carotene, Beta (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Cryptoxanthin, Beta (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: d3afc0c8-914f-46bd-9a73-6575b9d2101b
		summarizeBy: sum
		sourceColumn: Cryptoxanthin, Beta (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Lycopene (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: d2f46dbd-65b0-4c1b-aedb-6d5cf4573abe
		summarizeBy: sum
		sourceColumn: Lycopene (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Lutein + Zeaxanthin (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: 4c98d253-cbe2-4a58-aa0d-01525afc7e70
		summarizeBy: sum
		sourceColumn: Lutein + Zeaxanthin (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Vit E (mg)'
		dataType: double
		lineageTag: 59c8e27f-6bf4-4034-aab5-d8de67977eb4
		summarizeBy: sum
		sourceColumn: Vit E (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit E, added (mg)'
		dataType: double
		lineageTag: 3bbdf561-d315-4d11-947e-44b99c0be7ef
		summarizeBy: sum
		sourceColumn: Vit E, added (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit D (mcg)'
		dataType: double
		lineageTag: f68d6fb0-ddd2-4caf-8cc9-fe6886a09bf0
		summarizeBy: sum
		sourceColumn: Vit D (mcg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit K (mcg)'
		dataType: double
		lineageTag: 64e2f2b0-b881-467f-9cc0-c73195f60578
		summarizeBy: sum
		sourceColumn: Vit K (mcg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit C (mg)'
		dataType: double
		lineageTag: 52f5d9b4-49a4-4237-b656-3683263385a4
		summarizeBy: sum
		sourceColumn: Vit C (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Thiamin (mg)'
		dataType: double
		lineageTag: 7ace2585-bc55-4c64-9a44-7719fa8b00d0
		summarizeBy: sum
		sourceColumn: Thiamin (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Riboflavin (mg)'
		dataType: double
		lineageTag: 205b2ab6-ef9f-4f7b-abb0-6e789e041a43
		summarizeBy: sum
		sourceColumn: Riboflavin (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Niacin (mg)'
		dataType: double
		lineageTag: 7e6117c0-5da6-4358-a9cc-4307bed34384
		summarizeBy: sum
		sourceColumn: Niacin (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit B6 (mg)'
		dataType: double
		lineageTag: 09a97cbc-ee3c-4795-80f8-6d0c27577597
		summarizeBy: sum
		sourceColumn: Vit B6 (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Folate, Total (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: a49d8ae5-1c21-4ae3-b8c9-16c5391f4d60
		summarizeBy: sum
		sourceColumn: Folate, Total (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Folate, DFE (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: fc80ec2a-52f4-4a72-8857-8edc8caec55b
		summarizeBy: sum
		sourceColumn: Folate, DFE (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Folic Acid (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: c03d6073-f654-4b41-8769-16b0067b1234
		summarizeBy: sum
		sourceColumn: Folic Acid (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Folate, Food (mcg)'
		dataType: int64
		formatString: 0
		lineageTag: 0e8d853f-6a78-431f-9efe-51f8d41c5ec8
		summarizeBy: sum
		sourceColumn: Folate, Food (mcg)

		annotation SummarizationSetBy = Automatic

	column 'Vit B12 (mcg)'
		dataType: double
		lineageTag: b1d34446-4379-437a-aff9-e282fc21814c
		summarizeBy: sum
		sourceColumn: Vit B12 (mcg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Vit B12, added (mcg)'
		dataType: double
		lineageTag: b096c069-0267-41e9-93e7-8845b4089d10
		summarizeBy: sum
		sourceColumn: Vit B12, added (mcg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Choline (mg)'
		dataType: double
		lineageTag: b8bccafd-5541-437c-9f8f-afb12b1077e9
		summarizeBy: sum
		sourceColumn: Choline (mg)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Alcohol (g)'
		dataType: int64
		formatString: 0
		lineageTag: d47c3042-9712-4e43-9849-4804975667d5
		summarizeBy: sum
		sourceColumn: Alcohol (g)

		annotation SummarizationSetBy = Automatic

	column 'Caffeine (mg)'
		dataType: int64
		formatString: 0
		lineageTag: 33a86afa-9f56-4f85-9532-2c83ed5c2dad
		summarizeBy: sum
		sourceColumn: Caffeine (mg)

		annotation SummarizationSetBy = Automatic

	column 'Theobromine (mg)'
		dataType: int64
		formatString: 0
		lineageTag: f4c593da-dc83-4d58-b107-5830627573cd
		summarizeBy: sum
		sourceColumn: Theobromine (mg)

		annotation SummarizationSetBy = Automatic

	partition 'Nutritional Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\TARUN\OneDrive\Desktop\The_World_is_Going_Bananas_Tables.xlsx"), null, true),
				    #"Nutritional Data_Sheet" = Source{[Item="Nutritional Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Nutritional Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Food Code", Int64.Type}, {"Food Description", type text}, {"Number of Servings", Int64.Type}, {"Measure Description", type text}, {"Measure Weight (g)", type number}, {"Energy (kcal)", Int64.Type}, {"Protein (g)", type number}, {"Carbohydrate (g)", type number}, {"Total Fat (g)", type number}, {"Total Sugars (g)", type number}, {"Dietary Fiber (g)", type number}, {"Water (g)", type number}, {"Cholesterol (mg)", Int64.Type}, {"Total Saturated (g)", type number}, {"4:0 (g)", type number}, {"6:0 (g)", type number}, {"8:0 (g)", type number}, {"10:0 (g)", type number}, {"12:0 (g)", type number}, {"14:0 (g)", type number}, {"16:0 (g)", type number}, {"18:0 (g)", type number}, {"Total Monounsaturated (g)", type number}, {"16:1 (g)", type number}, {"18:1 (g)", type number}, {"20:1 (g)", type number}, {"22:1 (g)", type number}, {"Total Polyunsaturated (g)", type number}, {"18:2 (g)", type number}, {"18:3 (g)", type number}, {"18:4 (g)", Int64.Type}, {"20:4 (g)", type number}, {"20:5 n-3 (g)", type number}, {"22:5 n-3 (g)", type number}, {"22:6 n-3 (g)", type number}, {"Calcium (mg)", Int64.Type}, {"Iron (mg)", type number}, {"Magnesium (mg)", Int64.Type}, {"Phosphorus (mg)", Int64.Type}, {"Potassium (mg)", Int64.Type}, {"Sodium (mg)", Int64.Type}, {"Zinc (mg)", type number}, {"Copper (mg)", type number}, {"Selenium (mcg)", type number}, {"Vit A, RAE (mcg)", Int64.Type}, {"Retinol (mcg)", Int64.Type}, {"Carotene, Alpha (mcg)", Int64.Type}, {"Carotene, Beta (mcg)", Int64.Type}, {"Cryptoxanthin, Beta (mcg)", Int64.Type}, {"Lycopene (mcg)", Int64.Type}, {"Lutein + Zeaxanthin (mcg)", Int64.Type}, {"Vit E (mg)", type number}, {"Vit E, added (mg)", type number}, {"Vit D (mcg)", type number}, {"Vit K (mcg)", type number}, {"Vit C (mg)", type number}, {"Thiamin (mg)", type number}, {"Riboflavin (mg)", type number}, {"Niacin (mg)", type number}, {"Vit B6 (mg)", type number}, {"Folate, Total (mcg)", Int64.Type}, {"Folate, DFE (mcg)", Int64.Type}, {"Folic Acid (mcg)", Int64.Type}, {"Folate, Food (mcg)", Int64.Type}, {"Vit B12 (mcg)", type number}, {"Vit B12, added (mcg)", type number}, {"Choline (mg)", type number}, {"Alcohol (g)", Int64.Type}, {"Caffeine (mg)", Int64.Type}, {"Theobromine (mg)", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

