"""pbiscan Diff Markdown Renderer.

Renders DiffResult into GitHub and Azure DevOps pull-request markdown format with:
- Score badge / summary banner
- Category delta comparison table
- Finding transitions breakdown
- Quality gate decision box
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pbiscan.diff import DiffResult


class DiffMarkdownRenderer:
    """Renders DiffResult to GitHub/Azure DevOps Flavored Markdown."""

    def render(self, diff: DiffResult) -> str:
        lines: list[str] = []

        # 1. Header & Quality Gate Status
        status_badge = "🟢 **QUALITY GATE: PASS**" if diff.verdict.passed else "🔴 **QUALITY GATE: FAIL**"
        lines.append(f"## PBIP Sentinel Scan Diff — {diff.current_name}")
        lines.append("")
        lines.append(f"> {status_badge}")
        if not diff.verdict.passed:
            lines.append(">")
            for r in diff.verdict.reasons:
                lines.append(f"> ❌ **Failure Reason**: {r}")
        lines.append("")

        # 2. Executive Score Comparison Table
        base_s = f"{diff.score_drift.baseline_score:.1f}"
        curr_s = f"{diff.score_drift.current_score:.1f}"
        d_val = diff.score_drift.overall_delta
        delta_symbol = f"+{d_val:.1f}" if d_val > 0 else f"{d_val:.1f}"
        direction_icon = "📈" if d_val > 0 else ("📉" if d_val < 0 else "➖")

        lines.append("### 📊 Health Score Drift")
        lines.append("")
        lines.append("| Metric | Baseline | Current | Delta | Trend |")
        lines.append("| :--- | :---: | :---: | :---: | :---: |")
        lines.append(f"| **Overall Health Score** | **{base_s}** | **{curr_s}** | **`{delta_symbol}`** | {direction_icon} **{diff.score_drift.direction}** |")

        for cat, c_delta in diff.score_drift.category_deltas.items():
            b_cat = diff.score_drift.baseline_categories.get(cat, 100)
            c_cat = diff.score_drift.current_categories.get(cat, 100)
            sym = f"+{c_delta:.1f}" if c_delta > 0 else f"{c_delta:.1f}"
            icon = "🟢" if c_delta >= 0 else "🔴"
            lines.append(f"| {cat.capitalize()} Architecture | {b_cat} | {c_cat} | `{sym}` | {icon} |")
        lines.append("")

        # 3. Finding Transitions Summary Table
        n_cnt = len(diff.new_findings)
        r_cnt = len(diff.resolved_findings)
        p_cnt = len(diff.persistent_findings)
        m_cnt = len(diff.modified_findings)

        lines.append("### 🔍 Finding Transitions")
        lines.append("")
        lines.append("| Transition State | Count | Description |")
        lines.append("| :--- | :---: | :--- |")
        lines.append(f"| 🔴 **New Findings (`+`)** | **{n_cnt}** | Newly introduced issues requiring remediation |")
        lines.append(f"| 🟢 **Resolved Findings (`-`)** | **{r_cnt}** | Previous issues resolved in this revision |")
        lines.append(f"| 🟡 **Modified Severity (`Δ`)** | **{m_cnt}** | Existing issues with shifted severity thresholds |")
        lines.append(f"| ⚪ **Persistent Findings (`=`)** | **{p_cnt}** | Unchanged existing issues |")
        lines.append("")

        # 4. Detailed New Findings
        if diff.new_findings:
            lines.append("### 🔴 Newly Introduced Issues")
            lines.append("")
            lines.append("| Severity | Rule ID | Location | Diagnosis |")
            lines.append("| :--- | :--- | :--- | :--- |")
            for t in diff.new_findings:
                loc = t.location or "Global"
                lines.append(f"| `{t.severity}` | **`{t.rule_id}`** | `{loc}` | {t.title} |")
            lines.append("")

        # 5. Detailed Resolved Findings
        if diff.resolved_findings:
            lines.append("### 🟢 Resolved Issues")
            lines.append("")
            lines.append("| Previous Severity | Rule ID | Location | Title |")
            lines.append("| :--- | :--- | :--- | :--- |")
            for t in diff.resolved_findings:
                loc = t.location or "Global"
                lines.append(f"| `{t.severity}` | **`{t.rule_id}`** | `{loc}` | {t.title} |")
            lines.append("")

        # 6. Detailed Modified Findings
        if diff.modified_findings:
            lines.append("### 🟡 Modified Findings")
            lines.append("")
            lines.append("| Rule ID | Location | Baseline Severity | Current Severity |")
            lines.append("| :--- | :--- | :---: | :---: |")
            for t in diff.modified_findings:
                loc = t.location or "Global"
                lines.append(f"| **`{t.rule_id}`** | `{loc}` | `{t.baseline_severity}` | `{t.severity}` |")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by [PBIP Sentinel](https://github.com/KULLOLLITARUN/Power-BI-Report-Quality-Performance-Scanner)*")

        return "\n".join(lines)
