"""GitHub-optimized markdown renderer for PBIP Sentinel Safe Remediation Proposals (CI/CD)."""
from __future__ import annotations

import difflib
from typing import Optional

from pbiscan import __version__
from pbiscan.remediation.models import (
    PatchValidationResult,
    RemediationPlan,
    RemediationSafety,
)


class RemediationMarkdownRenderer:
    """Renders structured, collapsible GitHub PR comments for safe remediation proposals."""

    @classmethod
    def render(
        cls,
        plan: RemediationPlan,
        validation: PatchValidationResult,
        repo_relative_path: Optional[str] = None,
    ) -> str:
        """Render a GitHub Actions PR comment markdown document."""
        model_display_name = repo_relative_path or plan.model_path.name
        actionable_count = len(plan.actionable_patches)
        delta_str = f"+{validation.score_delta:.1f}" if validation.score_delta > 0 else f"{validation.score_delta:.1f}"
        
        gate_badge = "🟢 **PASSED (Safe to Apply)**" if validation.accepted else "🔴 **REJECTED (Failed Gates)**"
        if actionable_count == 0:
            gate_badge = "🟢 **CLEAN (No Remediation Required)**"

        lines: list[str] = [
            "## 🛡️ PBIP Sentinel — Safe Remediation Proposal",
            "",
            f"> **Automated code quality & performance proposal for `{model_display_name}`**",
            "",
            "| Metric | Baseline | Projected | Delta | Validation Gate |",
            "| :--- | :---: | :---: | :---: | :---: |",
            f"| **Overall Health Score** | `{validation.before_score:.1f}` | `{validation.after_score:.1f}` | **`{delta_str}`** | {gate_badge} |",
            f"| **Actionable Patches** | — | — | **`{actionable_count}`** | `{validation.resolved_count}` findings resolved |",
            "",
        ]

        if not plan.actionable_patches:
            lines.extend([
                "### ✨ Model is Clean",
                "No automated remediation patches are required for this project. All quality checks passed or are already compliant.",
                "",
                "---",
                f"*Generated by [PBIP Sentinel](https://github.com/KULLOLLITARUN/Power-BI-Report-Quality-Performance-Scanner) v{__version__}*",
            ])
            return "\n".join(lines)

        lines.append("### 📋 Proposed Remediation Patches")
        lines.append("")

        for idx, patch in enumerate(plan.actionable_patches, 1):
            risk_badge = "🟢 LOW" if patch.evidence.semantic_risk == "LOW" else ("🟡 MEDIUM" if patch.evidence.semantic_risk == "MEDIUM" else "🔴 HIGH")
            safety_badge = "🛡️ Safe Automated" if patch.safety == RemediationSafety.SAFE_AUTO else "⚠️ Review Required"
            
            lines.append("<details>")
            lines.append(f"<summary><b>🔧 [{idx}/{actionable_count}] <code>{patch.patch_id}</code> — {patch.rule_id} ({patch.file_path.name})</b></summary>")
            lines.append("")
            lines.append("| Property | Detail |")
            lines.append("| :--- | :--- |")
            lines.append(f"| **Rule ID** | `{patch.rule_id}` |")
            lines.append(f"| **Safety Classification** | {safety_badge} |")
            lines.append(f"| **Semantic Risk** | {risk_badge} |")
            lines.append(f"| **Target File** | `{patch.file_path.name}` |")
            if patch.evidence.affected_objects:
                lines.append(f"| **Affected Objects** | `{', '.join(patch.evidence.affected_objects)}` |")
            lines.append(f"| **Expected Effect** | {patch.evidence.expected_resolution or 'Resolves quality defect'} |")
            lines.append("")
            lines.append(f"**Rationale**: {patch.rationale}")
            lines.append("")
            lines.append("```diff")
            for c in patch.chunks:
                diff = difflib.unified_diff(
                    c.original_text.splitlines(keepends=True),
                    c.replacement_text.splitlines(keepends=True),
                    fromfile=f"a/{patch.file_path.name}",
                    tofile=f"b/{patch.file_path.name}",
                )
                lines.extend([d.rstrip("\n") for d in diff])
            lines.append("```")
            lines.append("")
            lines.append("**Apply locally:**")
            lines.append("```bash")
            lines.append(f"pbiscan fix \"{model_display_name}\" --patch-id {patch.patch_id} --apply")
            lines.append("```")
            lines.append("</details>")
            lines.append("")

        if validation.rejection_reasons:
            lines.append("### ⚠️ Validation Warnings / Rejections")
            for r in validation.rejection_reasons:
                lines.append(f"- ❌ {r}")
            lines.append("")

        lines.extend([
            "### 🚀 How to Apply These Remediations Locally",
            "",
            "To review and apply these validated fixes in your local workspace, run:",
            "```bash",
            "# Interactive review (step-by-step approval):",
            f"pbiscan fix \"{model_display_name}\" --interactive",
            "",
            "# Or apply all validated safe fixes at once:",
            f"pbiscan fix \"{model_display_name}\" --apply",
            "```",
            "",
            "---",
            f"*Generated by [PBIP Sentinel](https://github.com/KULLOLLITARUN/Power-BI-Report-Quality-Performance-Scanner) v{__version__} — Zero-Mutation CI Safety Policy Active*",
        ])

        return "\n".join(lines)
